#!/bin/bash

#
# 1.0 Inital Black&White stand status for MOTD
#
Sub1=10.1
Sub2=193.111
DiskToCheck=/dev/sda5


CMASpace=`df -h | grep $DiskToCheck | awk {'print $4'}`
CMAMemTotal=`/usr/bin/free -hm | grep Mem: | awk {'print $2'}`
CMAMemUsed=`/usr/bin/free -hm | grep Mem: | awk {'print $3'}`
CMAMemFree=`/usr/bin/free -hm | grep Mem: | awk {'print $4'}`
CMAMemAlailable=`/usr/bin/free -hm | grep Mem: | awk {'print $7'}`
Hostname=`cat /etc/hostname`
IP=`/sbin/ip a | grep -E "$Sub1|$Sub2" | grep -v secondary | awk {'print $2'}`

echo "
 ========================================

 Disk status            : $CMASpace
 Total memory           : $CMAMemTotal
 Uused memory           : $CMAMemUsed
 Free memory            : $CMAMemFree

 -------------------------------------

 VM hostname            : $Hostname
 VM IP address          : $IP
 Oracle database URL    : $IP:1521/DEPO
 Oracle TNS name        : SSYS
 Oracle main scheme     : DEPO
 System                 : DEPO3
 Startup script:        : /cma/main/adminDEPO

 -------------------------------------

 Server  URL            : http://$IP:8088/SSYSGw/gw
 Gateway URL            : http://$IP:7088/SSYSGw/gw
 TMSX URL               : https://$IP:8934/portal/
 PSWA URL               : http://$IP:8280/TMonWS/TMonWS
 DBO URL                : http://$IP:8180/DBOWS/DBOWS


 =========================================
"
